// Note: This is the list of formats
// The rules that formats use are stored in data/rulesets.ts

const RELUMI_BASE_BANLIST = [
	"pokemontag:mega",
	"pokemontag:gigantamax",
	"pokemontag:teraforme",
	"pokemontag:stellarforme",
	"pokemontag:pikachucap",
	"Revavroom-Caph Starmobile",
	"Revavroom-Navi Starmobile",
	"Revavroom-Ruchbah Starmobile",
	"Revavroom-Schedar Starmobile",
	"Revavroom-Segin Starmobile",
	"Araquanid-Totem",
	"Gumshoos-Totem",
	"Kommo-o-Totem",
	"Lurantis-Totem",
	"Mimikyu-Busted-Totem",
	"Mimikyu-Totem",
	"Raticate-Alola-Totem",
	"Ribombee-Totem",
	"Salazzle-Totem",
	"Togedemaru-Totem",
	"Vikavolt-Totem",
] as const;

const RELUMI_GEN9_UNBANLIST = [
	"Sprigatito",
	"Floragato",
	"Meowscarada",
	"Fuecoco",
	"Crocalor",
	"Skeledirge",
	"Quaxly",
	"Quaxwell",
	"Quaquaval",
	"Wooper-Paldea",
	"Clodsire",
	"Tauros-Paldea-Combat",
	"Tauros-Paldea-Blaze",
	"Tauros-Paldea-Aqua",
	"Ursaluna-Bloodmoon",
	"Farigiraf",
	"Dudunsparce",
	"Dudunsparce-Three-Segment",
	"Kingambit",
	"Annihilape",
	"Dipplin",
	"Hydrapple",
	"Archaludon",
] as const;

const RELUMI_OU_BANLIST = [
	"Mewtwo",
	"Mewtwo-Shadow",
	"Lugia",
	"Lugia-Shadow",
	"Ho-Oh",
	"Kyogre",
	"Groudon",
	"Groudon-Meta",
	"Rayquaza",
	"Rayquaza-Illusory",
	"Deoxys",
	"Deoxys-Attack",
	"Deoxys-Defense",
	"Deoxys-Speed",
	"Dialga",
	"Palkia",
	"Giratina",
	"Giratina-Origin",
	"Regigigas",
	"Darkrai",
	"Shaymin-Sky",
	"Arceus",
	"Arceus-Bug",
	"Arceus-Dark",
	"Arceus-Dragon",
	"Arceus-Electric",
	"Arceus-Fairy",
	"Arceus-Fighting",
	"Arceus-Fire",
	"Arceus-Flying",
	"Arceus-Ghost",
	"Arceus-Grass",
	"Arceus-Ground",
	"Arceus-Ice",
	"Arceus-Poison",
	"Arceus-Psychic",
	"Arceus-Rock",
	"Arceus-Steel",
	"Arceus-Water",
	"Reshiram",
	"Zekrom",
	"Landorus",
	"Kyurem-Black",
	"Kyurem-White",
	"Genesect",
	"Genesect-Burn",
	"Genesect-Chill",
	"Genesect-Douse",
	"Genesect-Shock",
	"Xerneas",
	"Xerneas-Neutral",
	"Yveltal",
	"Zygarde-Complete",
	"Solgaleo",
	"Lunala",
	"Necrozma-Dawn-Wings",
	"Necrozma-Dusk-Mane",
	"Pheromosa",
	"Magearna",
	"Magearna-Original",
	"Marshadow",
	"Naganadel",
	"Zacian",
	"Zacian-Crowned",
	"Zamazenta",
	"Zamazenta-Crowned",
	"Urshifu",
	"Spectrier",
	"Calyrex-Ice",
	"Calyrex-Shadow",
	"Eternatus",
	"Necrozma-Ultra",
	"Dialga-Origin",
	"Palkia-Origin",
	"Melmetal",
] as const;

export const Formats: import("../sim/dex-formats").FormatList = [
	{
		section: "Relumi Singles",
	},
	{
		name: "[Gen 8] Relumi Singles Random",
		desc: `Randomized teams for the Relumi metagame.`,
		mod: "gen8relumi",
		team: "random",
		bestOfDefault: true,
		ruleset: [
			"Dynamax Clause",
			"HP Percentage Mod",
			"Cancel Mod",
			"Illusion Level Mod",
		],
	},
	{
		name: "[Gen 8] Relumi Singles Testing",
		mod: "gen8relumi",
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: [
			"Dynamax Clause",
			"Team Preview",
			"Cancel Mod",
			"Max Team Size = 24",
			"Max Move Count = 24",
			"Max Level = 9999",
			"Default Level = 100",
		],
	},
	{
		name: "[Gen 8] Relumi Singles Anything Goes",
		mod: "gen8relumi",
		banlist: [...RELUMI_BASE_BANLIST],
		ruleset: [
			"Standard",
			"Dynamax Clause",
			"Allow Tradeback",
			"+Past",
			"+Future",
			"+LGPE",
		],
	},
	{
		name: "[Gen 8] Relumi Singles Ubers",
		mod: "gen8relumi",
		ruleset: [
			"Standard",
			"Dynamax Clause",
			"Allow Tradeback",
			"+Past",
			"+Future",
			"+LGPE",
		],
		banlist: [...RELUMI_BASE_BANLIST, "pokemontag:futurepokemon"],
		unbanlist: [...RELUMI_GEN9_UNBANLIST],
	},
	{
		name: "[Gen 8] Relumi Singles OU",
		mod: "gen8relumi",
		ruleset: [
			"Standard",
			"Dynamax Clause",
			"Allow Tradeback",
			"+Past",
			"+Future",
			"+LGPE",
		],
		banlist: [...RELUMI_BASE_BANLIST, "pokemontag:futurepokemon", ...RELUMI_OU_BANLIST],
		unbanlist: [...RELUMI_GEN9_UNBANLIST],
	},
	{
		section: "Relumi Doubles",
	},
	{
		name: "[Gen 8] Relumi Doubles Random",
		mod: "gen8relumi",
		gameType: "doubles",
		team: "random",
		bestOfDefault: true,
		ruleset: [
			"Dynamax Clause",
			"HP Percentage Mod",
			"Cancel Mod",
			"Illusion Level Mod",
		],
	},
	{
		name: "[Gen 8] Relumi Doubles Testing",
		mod: "gen8relumi",
		gameType: "doubles",
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: [
			"Dynamax Clause",
			"Team Preview",
			"Cancel Mod",
			"Max Team Size = 24",
			"Max Move Count = 24",
			"Max Level = 9999",
			"Default Level = 100",
		],
	},
	{
		name: "[Gen 8] Relumi Doubles Anything Goes",
		mod: "gen8relumi",
		gameType: "doubles",
		banlist: [...RELUMI_BASE_BANLIST],
		ruleset: [
			"Standard Doubles",
			"Dynamax Clause",
			"Allow Tradeback",
			"+Past",
			"+Future",
			"+LGPE",
		],
	},
	{
		name: "[Gen 8] Relumi Doubles Ubers",
		mod: "gen8relumi",
		gameType: "doubles",
		ruleset: [
			"Standard Doubles",
			"Dynamax Clause",
			"Allow Tradeback",
			"+Past",
			"+Future",
			"+LGPE",
		],
		banlist: [...RELUMI_BASE_BANLIST, "pokemontag:futurepokemon"],
		unbanlist: [...RELUMI_GEN9_UNBANLIST],
	},
	{
		name: "[Gen 8] Relumi Doubles OU",
		mod: "gen8relumi",
		gameType: "doubles",
		ruleset: [
			"Standard Doubles",
			"Dynamax Clause",
			"Allow Tradeback",
			"+Past",
			"+Future",
			"+LGPE",
		],
		banlist: [...RELUMI_BASE_BANLIST, "pokemontag:futurepokemon", ...RELUMI_OU_BANLIST],
		unbanlist: [...RELUMI_GEN9_UNBANLIST],
	},
];
