// Note: This is the list of formats
// The rules that formats use are stored in data/rulesets.ts

export const Formats: import("../sim/dex-formats").FormatList = [
	{
		section: "Relumi",
	},
	{
		name: "[Gen 8 Relumi] Random Battle",
		desc: `Randomized teams for the Relumi metagame.`,
		mod: "gen8relumi",
		team: "random",
		bestOfDefault: true,
		ruleset: [
			"Dynamax Clause",
			"HP Percentage Mod",
			"Cancel Mod",
			"Illusion Level Mod",
		],
	},
	{
		name: "[Gen 8 Relumi] Random Doubles Battle",
		mod: "gen8relumi",
		gameType: "doubles",
		team: "random",
		bestOfDefault: true,
		ruleset: [
			"Dynamax Clause",
			"HP Percentage Mod",
			"Cancel Mod",
			"Illusion Level Mod",
		],
	},
	{
		name: "[Gen 8 Relumi] Singles Testing",
		mod: "gen8relumi",
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: [
			"Dynamax Clause",
			"Team Preview",
			"Cancel Mod",
			"Max Team Size = 24",
			"Max Move Count = 24",
			"Max Level = 9999",
			"Default Level = 100",
		],
	},
	{
		name: "[Gen 8 Relumi] Doubles Testing",
		mod: "gen8relumi",
		gameType: "doubles",
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: [
			"Dynamax Clause",
			"Team Preview",
			"Cancel Mod",
			"Max Team Size = 24",
			"Max Move Count = 24",
			"Max Level = 9999",
			"Default Level = 100",
		],
	},
	{
		name: "[Gen 8 Relumi] Singles",
		mod: "gen8relumi",
		banlist: [
			"pokemontag:mega",
			"pokemontag:gigantamax",
			"Revavroom-Caph Starmobile",
			"Revavroom-Navi Starmobile",
			"Revavroom-Ruchbah Starmobile",
			"Revavroom-Schedar Starmobile",
			"Revavroom-Segin Starmobile",
		],
		ruleset: [
			"Standard",
			"Dynamax Clause",
			"Allow Tradeback",
			"+Past",
			"+Future",
			"+LGPE",
		],
	},
	{
		name: "[Gen 8 Relumi] Doubles",
		mod: "gen8relumi",
		gameType: "doubles",
		banlist: [
			"pokemontag:mega",
			"pokemontag:gigantamax",
			"Revavroom-Caph Starmobile",
			"Revavroom-Navi Starmobile",
			"Revavroom-Ruchbah Starmobile",
			"Revavroom-Schedar Starmobile",
			"Revavroom-Segin Starmobile",
		],
		ruleset: [
			"Standard Doubles",
			"Dynamax Clause",
			"Allow Tradeback",
			"+Past",
			"+Future",
			"+LGPE",
		],
	},
];
